server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: postservice
        uri: http://localhost:8081/
        predicates:
        - Path=/posts/**
      - id: commentservice
        uri: http://localhost:8082/
        predicates:
        - Path=/comments/**
     